spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: mircoservicecloud-config-atguigu-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test